<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net10.0</TargetFrameworks>
    <IsPackable>false</IsPackable>
    <LangVersion>latest</LangVersion>
    <Platforms>AnyCPU;x64;x86</Platforms>
  </PropertyGroup>

  <PropertyGroup>
    <SharedAssetsBaseDir>$([System.IO.Path]::GetFullPath( $(EnlistmentRoot)\shared\ ))</SharedAssetsBaseDir>
    <SharedSrcBaseDir>$([System.IO.Path]::GetFullPath( $(SharedAssetsBaseDir)\src\managed-src\ ))</SharedSrcBaseDir>
    <SharedSrcBaseLabel>Shared-Src</SharedSrcBaseLabel>
  </PropertyGroup>

  <PropertyGroup>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>$(SharedAssetsBaseDir)\resources\Datadog.Trace.snk</AssemblyOriginatorKeyFile>
    <DelaySign>false</DelaySign>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="xunit.runner.json" />
    <Content Include="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentAssertions" Version="6.12.0" />
    <PackageReference Include="Google.Protobuf" Version="3.20.1" />
    <PackageReference Include="K4os.Compression.LZ4.Streams" Version="1.3.6" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.3.2" />
    <!-- Override the vulnerable Newtonsoft.Json version pulled by the old test SDK. -->
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="xunit" Version="2.4.2" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.3">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
     <PackageReference Include="ZstdSharp.Port" Version="0.8.6" />
  </ItemGroup>
</Project>
