services:
  pyroscope:
    image: pyroscope/pyroscope:latest
    ports:
      - "4040:4040"
    command:
      - "server"
    environment:
      - PYROSCOPE_LOG_LEVEL=debug
    volumes:
      - pyroscope-data:/var/lib/pyroscope

  pyroscope-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - pyroscope
    environment:
      # Application settings
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000

      # Pyroscope configuration - pointing to local server
      - PYROSCOPE_APPLICATION_NAME=napiv1
      - PYROSCOPE_LABELS=environment:${ENVIRONMENT:-dev},region:${REGION:-us-west}
      - PYROSCOPE_PROFILING_ENABLED=1
      - PYROSCOPE_LOG_LEVEL=debug
      - PYROSCOPE_PROFILING_ALLOCATION_ENABLED=true
      - PYROSCOPE_PROFILING_CONTENTION_ENABLED=true
      - PYROSCOPE_PROFILING_EXCEPTION_ENABLED=true
      - PYROSCOPE_SERVER_ADDRESS=http://pyroscope:4040

      # .NET Core profiling settings
      - CORECLR_ENABLE_PROFILING=1
      - CORECLR_PROFILER={BD1A650D-AC5D-4896-B64F-D6FA25D6B26A}
      - CORECLR_PROFILER_PATH=/app/runtimes/linux-x64/native/Pyroscope.Profiler.Native.so
      - LD_PRELOAD=/app/runtimes/linux-x64/native/Pyroscope.Linux.ApiWrapper.x64.so
    volumes:
      - pyroscope-logs:/var/log/pyroscope
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/Pyroscope/Health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

volumes:
  pyroscope-logs:
  pyroscope-data: