name: Build linux profiler

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches: [main]

permissions:
  contents: read


jobs:
  build-linux-profiler-x86_64:
    if: github.event.action != 'labeled' || contains(github.event.pull_request.labels.*.name, 'pr-publish-dev-docker')
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-x64-large
    env:
      DOCKER_BUILDKIT: 1
    strategy:
      fail-fast: false
      matrix:
        name: ['glibc', 'musl']
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: 'true'
          persist-credentials: false
      - run: RELEASE_VERSION=dev-$(git rev-parse --short HEAD) ARCH=x86_64 LIBC=${{ matrix.name }}  make docker/build
      - uses: grafana/shared-workflows/actions/get-vault-secrets@e7a3275d4c4978a3514801ec55708f1c599a6906
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'pr-publish-dev-docker') && github.event.pull_request.head.repo.full_name == github.repository
        with:
          repo_secrets: |
            DOCKERHUB_USERNAME=dockerhub:user
            DOCKERHUB_PASSWORD=dockerhub:token
      - uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'pr-publish-dev-docker') && github.event.pull_request.head.repo.full_name == github.repository
        name: Login to Docker Hub
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}
      - if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'pr-publish-dev-docker') && github.event.pull_request.head.repo.full_name == github.repository
        run: RELEASE_VERSION=dev-$(git rev-parse --short HEAD) ARCH=x86_64 LIBC=${{ matrix.name }}  make docker/push
  build-linux-profiler-aarch64:
    if: github.event.action != 'labeled' || contains(github.event.pull_request.labels.*.name, 'pr-publish-dev-docker')
    permissions:
      contents: read
      id-token: write
    runs-on: ubuntu-arm64-large
    env:
      DOCKER_BUILDKIT: 1
    strategy:
      fail-fast: false
      matrix:
        name: ['glibc', 'musl']
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: 'true'
          persist-credentials: false
      - uses: actions/setup-dotnet@131b410979e0b49e2162c0718030257b22d6dc2c
        with:
          dotnet-version: '8.0.412'
      - run: RELEASE_VERSION=dev-$(git rev-parse --short HEAD) ARCH=aarch64 LIBC=${{ matrix.name }}  make docker/build
      - uses: grafana/shared-workflows/actions/get-vault-secrets@e7a3275d4c4978a3514801ec55708f1c599a6906
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'pr-publish-dev-docker') && github.event.pull_request.head.repo.full_name == github.repository
        with:
          repo_secrets: |
            DOCKERHUB_USERNAME=dockerhub:user
            DOCKERHUB_PASSWORD=dockerhub:token
      - uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'pr-publish-dev-docker') && github.event.pull_request.head.repo.full_name == github.repository
        name: Login to Docker Hub
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}
      - if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'pr-publish-dev-docker') && github.event.pull_request.head.repo.full_name == github.repository
        run: RELEASE_VERSION=dev-$(git rev-parse --short HEAD) ARCH=aarch64 LIBC=${{ matrix.name }}  make docker/push
  publish-dev-manifest:
    permissions:
      contents: read
      id-token: write
    if: github.event_name == 'push' && github.ref == 'refs/heads/main' || github.event_name == 'pull_request' && contains(github.event.pull_request.labels.*.name, 'pr-publish-dev-docker') && github.event.pull_request.head.repo.full_name == github.repository
    needs: [build-linux-profiler-x86_64, build-linux-profiler-aarch64]
    runs-on: ubuntu-x64-small
    env:
      DOCKER_BUILDKIT: 1
    strategy:
      fail-fast: false
      matrix:
        name: ['glibc', 'musl']
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: 'true'
          persist-credentials: false
      - uses: grafana/shared-workflows/actions/get-vault-secrets@e7a3275d4c4978a3514801ec55708f1c599a6906
        with:
          repo_secrets: |
            DOCKERHUB_USERNAME=dockerhub:user
            DOCKERHUB_PASSWORD=dockerhub:token
      - uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        name: Login to Docker Hub
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_PASSWORD }}
      - run: RELEASE_VERSION=dev-$(git rev-parse --short HEAD) LIBC=${{ matrix.name }}  make docker/manifest
