name: Build linux

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Build docker image
        uses: docker/build-push-action@v3
        with:
          tags: test-image:latest
          push: false
          file: ./Pyroscope.Dockerfile

