name: Publish dev Docker images

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, labeled]
    branches: [main]

permissions:
  contents: read

jobs:
  publish-dev:
    if:
      github.event_name == 'push' ||
      (contains(github.event.pull_request.labels.*.name, 'pr-publish-dev-docker') &&
      github.event.pull_request.head.repo.full_name == github.repository &&
      (github.event.action != 'labeled' || github.event.label.name == 'pr-publish-dev-docker'))
    permissions:
      contents: read
      id-token: write
    runs-on: ${{ matrix.runner }}
    env:
      DOCKER_BUILDKIT: 1
      RELEASE_VERSION: dev-${{ github.event.pull_request.head.sha || github.sha }}
      ARCH: ${{ matrix.arch }}
      LIBC: ${{ matrix.libc }}
    strategy:
      fail-fast: false
      matrix:
        libc: ['glibc', 'musl']
        arch: ['x86_64', 'aarch64']
        include:
          - arch: x86_64
            runner: ${{ github.repository_owner == 'grafana' && 'ubuntu-x64-large' || 'ubuntu-latest' }}
          - arch: aarch64
            runner: ${{ github.repository_owner == 'grafana' && 'ubuntu-arm64-large' || 'ubuntu-24.04-arm' }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          submodules: 'true'
          persist-credentials: false
      - uses: actions/setup-dotnet@131b410979e0b49e2162c0718030257b22d6dc2c
        if: matrix.arch == 'aarch64'
      - run: make docker/build
      - name: Login to DockerHub (from vault)
        uses: grafana/shared-workflows/actions/dockerhub-login@081a366728379fd0426b9cfef190e9a21c2d5418 # dockerhub-login/v1.0.3
      - run: make docker/push
  publish-dev-manifest:
    permissions:
      contents: read
      id-token: write
    needs: [publish-dev]
    runs-on: ${{ github.repository_owner == 'grafana' && 'ubuntu-x64-small' || 'ubuntu-latest' }}
    env:
      DOCKER_BUILDKIT: 1
      RELEASE_VERSION: dev-${{ github.event.pull_request.head.sha || github.sha }}
      LIBC: ${{ matrix.libc }}
    strategy:
      fail-fast: false
      matrix:
        libc: ['glibc', 'musl']
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
          submodules: 'true'
          persist-credentials: false
      - name: Login to DockerHub (from vault)
        uses: grafana/shared-workflows/actions/dockerhub-login@081a366728379fd0426b9cfef190e9a21c2d5418 # dockerhub-login/v1.0.3
      - run: make docker/manifest
