name: Release Publish

on:
  release:
    types: [published]

jobs:
  docker-promote:
    permissions:
      contents: read
      id-token: write
    if: contains(github.event.release.tag_name, '-pyroscope')
    runs-on: ${{ github.repository_owner == 'grafana' && 'ubuntu-x64-small' || 'ubuntu-latest' }}
    env:
      DOCKER_IMAGE: ${{ github.repository_owner == 'grafana' && 'pyroscope/pyroscope-dotnet' || 'anatolykorniltsev622/pyroscope-dotnet' }}
      LIBC: ${{ matrix.libc }}
    strategy:
      matrix:
        libc: ['glibc', 'musl']
    steps:
      - uses: grafana/shared-workflows/actions/get-vault-secrets@e7a3275d4c4978a3514801ec55708f1c599a6906
        if: github.repository_owner == 'grafana'
        with:
          repo_secrets: |
            DOCKERHUB_USERNAME=dockerhub:user
            DOCKERHUB_PASSWORD=dockerhub:token
      - uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3.7.0
        name: Login to Docker Hub
        with:
          username: ${{ env.DOCKERHUB_USERNAME || secrets.DOCKERHUB_USERNAME }} # secrets used on forks
          password: ${{ env.DOCKERHUB_PASSWORD || secrets.DOCKERHUB_PASSWORD }} # secrets used on forks
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Promote draft Docker tags
        run: RELEASE_VERSION=$(.github/scripts/version.sh) make docker/promote

  # TODO: switch to trusted publishing https://github.com/grafana/pyroscope-dotnet/issues/119
  nuget-publish:
    permissions:
      contents: read
      id-token: write
    if: contains(github.event.release.tag_name, '-pyroscope')
    runs-on: ${{ github.repository_owner == 'grafana' && 'ubuntu-x64-small' || 'ubuntu-latest' }}
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-dotnet@131b410979e0b49e2162c0718030257b22d6dc2c
        with:
          global-json-file: global.json
      - name: Download NuGet package from release
        run: gh release download "$TAG_NAME" --pattern 'Pyroscope*.nupkg' --dir ./packages
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
      - uses: grafana/shared-workflows/actions/get-vault-secrets@e7a3275d4c4978a3514801ec55708f1c599a6906
        if: github.repository_owner == 'grafana'
        with:
          repo_secrets: |
            NUGET_API_KEY=nuget:api_key
      - name: Publish to nuget.org
        run: dotnet nuget push ./packages/Pyroscope*.nupkg -k "${NUGET_API_KEY}" -s https://api.nuget.org/v3/index.json
