name: Release Publish

on:
  release:
    types: [published]

jobs:
  docker-promote:
    permissions:
      contents: read
      id-token: write
    if: contains(github.event.release.tag_name, '-pyroscope')
    runs-on: ${{ github.repository_owner == 'grafana' && 'ubuntu-x64-small' || 'ubuntu-latest' }}
    env:
      LIBC: ${{ matrix.libc }}
    strategy:
      matrix:
        libc: ['glibc', 'musl']
    steps:
      - name: Login to DockerHub (from vault)
        uses: grafana/shared-workflows/actions/dockerhub-login@081a366728379fd0426b9cfef190e9a21c2d5418 # dockerhub-login/v1.0.3
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Promote draft Docker tags
        run: RELEASE_VERSION=$(.github/scripts/version.sh) make docker/promote

  # TODO: switch to trusted publishing https://github.com/grafana/pyroscope-dotnet/issues/119
  nuget-publish:
    permissions:
      contents: read
      id-token: write
    if: contains(github.event.release.tag_name, '-pyroscope')
    runs-on: ${{ github.repository_owner == 'grafana' && 'ubuntu-x64-small' || 'ubuntu-latest' }}
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: actions/setup-dotnet@131b410979e0b49e2162c0718030257b22d6dc2c
        with:
          global-json-file: global.json
      - name: Download NuGet package from release
        run: gh release download "$TAG_NAME" --pattern 'Pyroscope*.nupkg' --dir ./packages
        env:
          TAG_NAME: ${{ github.event.release.tag_name }}
      - uses: grafana/shared-workflows/actions/get-vault-secrets@e7a3275d4c4978a3514801ec55708f1c599a6906
        if: github.repository_owner == 'grafana'
        with:
          repo_secrets: |
            NUGET_API_KEY=nuget:api_key
      - name: Publish to nuget.org
        run: dotnet nuget push ./packages/Pyroscope*.nupkg -k "${NUGET_API_KEY}" -s https://api.nuget.org/v3/index.json
