name: Release managed helper

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  release-managed-helper:
    runs-on: ${{ github.repository_owner == 'grafana' && 'ubuntu-x64-small' || 'ubuntu-latest' }}
    env:
      RELEASE_VERSION: ${{ github.event.release.tag_name }}
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: 'true'
          persist-credentials: false
      - uses: actions/setup-dotnet@131b410979e0b49e2162c0718030257b22d6dc2c
        with:
          global-json-file: global.json
      - run: make bump_version
      - name: Check version matches committed version
        if: ${{ !contains(github.event.release.tag_name, '-rc') }}
        run: git diff --exit-code
      - run: dotnet build -c Release ./Pyroscope
        working-directory: Pyroscope
      - name: Upload NuGet packages
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
        with:
          name: packages
          path: ./Pyroscope/artifacts/package/release
          if-no-files-found: error
      - name: Upload artifacts to release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          files: |
            ./Pyroscope/artifacts/bin/Pyroscope/release/Pyroscope.dll
            ./Pyroscope/artifacts/package/release/Pyroscope*.nupkg
