name: Release linux profiler

on:
  release:
    types: [created]

jobs:
  release-linux-profiler:
    permissions:
      contents: write
    runs-on: ${{ matrix.arch == 'aarch64' && (github.repository_owner == 'grafana' && 'ubuntu-arm64-large' || 'ubuntu-24.04-arm') || (github.repository_owner == 'grafana' && 'ubuntu-x64-large' || 'ubuntu-latest') }}
    env:
      DOCKER_BUILDKIT: 1
      ARCH: ${{ matrix.arch }}
      LIBC: ${{ matrix.libc }}
      RELEASE_VERSION: ${{ github.event.release.tag_name }}
    strategy:
      matrix:
        arch: ['x86_64', 'aarch64']
        libc: ['glibc', 'musl']
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: 'true'
          persist-credentials: false
      - run: make bump_version
      - name: Check version matches committed version
        if: ${{ !contains(github.event.release.tag_name, '-rc') }}
        run: git diff --exit-code
      - run: make docker/archive
      - name: Upload artifacts to release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2.5.0
        with:
          files: ./*.tar.gz
